import { PlatformName } from './types';

export const TITLE_MIN_LENGTH = 70;
export const TITLE_MAX_LENGTH = 80;

export const REQUIRED_DEPOP_HASHTAGS = 5;
export const REQUIRED_MERCARI_HASHTAGS = 3;
export const REQUIRED_POSHMARK_STYLE_TAGS = 3;
export const REQUIRED_ETSY_TAGS = 13;

export const DEPOP_AESTHETIC_MODE_NOT_APPLICABLE =
  'Not applicable - non-style-led item';

export const DEPOP_AESTHETIC_MODE_LIST = [
  'COQUETTE',
  'BALLETCORE',
  'SOFT GIRL',
  'ROMANTIC-FEMININE',
  'CLEAN GIRL',
  'MINIMALIST',
  'NORMCORE',
  'SCANDI MINIMAL',
  'Y2K',
  'MCBLING',
  'INDIE SLEAZE',
  'DOWNTOWN GIRL',
  '90s MINIMAL',
  '70s VINTAGE',
  'BLOKETTE',
  'TENNISCORE',
  'ATHLEISURE',
  'RETRO ATHLETIC',
  'GORPCORE',
  'TECHWEAR-LITE',
  'GRUNGE',
  'ALT',
  'PUNK',
  'BIKERCORE',
  'GOTH',
  'WHIMSYGOTH',
  'DARK ACADEMIA',
  'BOHO',
  'COTTAGECORE',
  'FAIRYCORE',
  'PRAIRIE',
  'WESTERN-INSPIRED',
  'COASTAL',
  'PREPPY',
  'OLD MONEY',
] as const;

export const POSHMARK_STYLE_TAG_MASTER_LIST = [
  '70s',
  '80s',
  '90s',
  'Activewear',
  'Animal Print',
  'Athleisure',
  'Avant Garde',
  'Baggy',
  'Balletcore',
  'Beach',
  'Beaded',
  'Bikercore',
  'Blokecore',
  'Bodycon',
  'Bohemian',
  'Bow',
  'Bridal',
  'Bridesmaid',
  'Business Casual',
  'Cable Knit',
  'Cashmere',
  'Casual',
  'Chunky',
  'Collegiate',
  'Colorblock',
  'Colorful',
  'Contemporary',
  'Coord Sets',
  'Coquette Girl',
  'Corduroy',
  'Cottagecore',
  'Cozy',
  'Crochet',
  'Cropped',
  'Cruelty-Free',
  'Cut Out',
  'Denim',
  'Distressed',
  'DIY',
  'Drop Waist',
  'Eclectic Grandpa',
  'Embroidered',
  'Fall',
  'Faux Fur',
  'Feminine',
  'Festival',
  'Festive',
  'Flannel',
  'Flare',
  'Floral',
  'Formal',
  'Fringe',
  'Gingham',
  'Girlhoodcore',
  'Gorpcore',
  'Goth',
  'Grunge',
  'Hand Knit',
  'Handmade',
  'Herringbone',
  'Houndstooth',
  'Indie Sleeze',
  'Knit',
  'Lace',
  'Leather',
  'Leopard Print',
  'Lightweight',
  'Linen',
  'Luxury',
  'Maximalism',
  'Mesh',
  'Metallic',
  'Minimalist',
  'Monochrome',
  'Monogram',
  'Moto',
  'Neon',
  'Neutral',
  'Nylon',
  'Office',
  'Oversized',
  'Paisley',
  'Party',
  'Pastel',
  'Patchwork',
  'Peplum',
  'Plaid',
  'Platform',
  'Pleated',
  'Polka Dot',
  'Preppy',
  'Punk',
  'Quiet Luxury',
  'Quilted',
  'Relaxed Fit',
  'Resortwear',
  'Retro',
  'Rosette',
  'Ruffle',
  'Satin',
  'Sequins',
  'Sheer',
  'Sherpa',
  'Silk',
  'Sporty',
  'Strapless',
  'Streetwear',
  'Stripes',
  'Suede',
  'Tailored',
  'Tennis Prep',
  'Travel',
  'Tropical',
  'Tweed',
  'Two-Tone',
  'Unisex',
  'Upcycled',
  'Utility',
  'Vacation',
  'Vegan',
  'Velour',
  'Vintage',
  'Waterproof',
  'Wedding',
  'Western',
  'Whimsigoth',
  'Winter',
  'Wool',
  'Woven',
  'Y2K',
] as const;

export const STANDARD_FOOTER =
  'Ships within one day after payment is received. Please see all pictures before purchasing. Stock photo is for reference only and may differ slightly from the actual item.';

export const JEWELRY_FOOTER =
  'Ships within one business day after purchase. Displays & boxes shown are not included.';

export const PLATFORM_ORDER: PlatformName[] = [
  'ebay',
  'depop',
  'poshmark',
  'mercari',
  'etsy',
];

export const SECTION_HEADER_ALIASES: Record<PlatformName, string[]> = {
  ebay: ['ebay', 'eBay', 'EBAY'],
  depop: ['depop', 'Depop', 'DEPOP'],
  poshmark: ['poshmark', 'Poshmark', 'POSHMARK'],
  mercari: ['mercari', 'Mercari', 'MERCARI'],
  etsy: ['etsy', 'Etsy', 'ETSY'],
};

export const LABELS = {
  ebay: {
    titleA: ['Title A'],
    titleB: ['Title B'],
    category: ['Category'],
    itemSpecifics: ['Item Specifics', 'Item Specifics Block'],
    description: ['Description'],
    measurements: ['Approximate Measurements', 'Measurements'],
  },
  depop: {
    aestheticMode: ['Aesthetic Mode'],
    attributes: ['Attributes'],
    listingBlock: ['Listing Block', 'Listing'],
    hashtags: ['Hashtags'],
    optionalBrandHashtags: ['Optional Brand Hashtags', 'Brand Hashtags'],
    measurements: ['Approximate Measurements', 'Measurements'],
  },
  poshmark: {
    title: ['Title'],
    description: ['Description'],
    styleTags: ['Style Tags'],
    compactAlt: ['Compact 3-Tag Strategy (Alt Option)', 'Compact 3-Tag Strategy'],
    measurements: ['Approximate Measurements', 'Measurements'],
  },
  mercari: {
    title: ['Title'],
    description: ['Description'],
    hashtags: ['Hashtags'],
    measurements: ['Approximate Measurements', 'Measurements'],
  },
  etsy: {
    title: ['Title'],
    category: ['Category'],
    materials: ['Materials'],
    attributesKeyDetails: ['Attributes / Key Details', 'Attributes/Key Details', 'Key Details'],
    tags: ['Tags'],
    description: ['Description'],
    measurements: ['Approximate Measurements', 'Measurements'],
  },
} as const;

export const KNOWN_FIELD_LABELS: string[] = Array.from(
  new Set(
    Object.values(LABELS).flatMap((platformLabels) =>
      Object.values(platformLabels).flatMap((labelList) => labelList),
    ),
  ),
);
